 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

module PhcdevworksCoreModules
  RSpec.describe "/affiliate/links", type: :request do
    # Affiliate::Link. As you add validations to Affiliate::Link, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      skip("Add a hash of attributes valid for your model")
    }

    let(:invalid_attributes) {
      skip("Add a hash of attributes invalid for your model")
    }

    describe "GET /index" do
      it "renders a successful response" do
        Affiliate::Link.create! valid_attributes
        get affiliate_links_url
        expect(response).to be_successful
      end
    end

    describe "GET /show" do
      it "renders a successful response" do
        link = Affiliate::Link.create! valid_attributes
        get affiliate_link_url(affiliate_link)
        expect(response).to be_successful
      end
    end

    describe "GET /new" do
      it "renders a successful response" do
        get new_affiliate_link_url
        expect(response).to be_successful
      end
    end

    describe "GET /edit" do
      it "render a successful response" do
        link = Affiliate::Link.create! valid_attributes
        get edit_affiliate_link_url(affiliate_link)
        expect(response).to be_successful
      end
    end

    describe "POST /create" do
      context "with valid parameters" do
        it "creates a new Affiliate::Link" do
          expect {
            post affiliate_links_url, params: { affiliate_link: valid_attributes }
          }.to change(Affiliate::Link, :count).by(1)
        end

        it "redirects to the created affiliate_link" do
          post affiliate_links_url, params: { affiliate_link: valid_attributes }
          expect(response).to redirect_to(affiliate_link_url(@affiliate_link))
        end
      end

      context "with invalid parameters" do
        it "does not create a new Affiliate::Link" do
          expect {
            post affiliate_links_url, params: { affiliate_link: invalid_attributes }
          }.to change(Affiliate::Link, :count).by(0)
        end

        it "renders a successful response (i.e. to display the 'new' template)" do
          post affiliate_links_url, params: { affiliate_link: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    describe "PATCH /update" do
      context "with valid parameters" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested affiliate_link" do
          link = Affiliate::Link.create! valid_attributes
          patch affiliate_link_url(affiliate_link), params: { affiliate_link: new_attributes }
          link.reload
          skip("Add assertions for updated state")
        end

        it "redirects to the affiliate_link" do
          link = Affiliate::Link.create! valid_attributes
          patch affiliate_link_url(affiliate_link), params: { affiliate_link: new_attributes }
          link.reload
          expect(response).to redirect_to(affiliate_link_url(link))
        end
      end

      context "with invalid parameters" do
        it "renders a successful response (i.e. to display the 'edit' template)" do
          link = Affiliate::Link.create! valid_attributes
          patch affiliate_link_url(affiliate_link), params: { affiliate_link: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    describe "DELETE /destroy" do
      it "destroys the requested affiliate_link" do
        link = Affiliate::Link.create! valid_attributes
        expect {
          delete affiliate_link_url(affiliate_link)
        }.to change(Affiliate::Link, :count).by(-1)
      end

      it "redirects to the affiliate_links list" do
        link = Affiliate::Link.create! valid_attributes
        delete affiliate_link_url(affiliate_link)
        expect(response).to redirect_to(affiliate_links_url)
      end
    end
  end
end
